### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/powershell#131]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [ ] [Configure online editor](https://github.com/exercism/powershell/issues/122)
- [ ] [Add key features](https://github.com/exercism/powershell/issues/123)
- [ ] [Add tags](https://github.com/exercism/powershell/issues/124)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/powershell/issues/125)
- [ ] [Update status of track](https://github.com/exercism/powershell/issues/129)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/powershell/issues/130)
- [ ] [Pass linting checks](https://github.com/exercism/powershell/issues/126)
- [ ] [Build Test Runner](https://github.com/exercism/powershell/issues/127)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/powershell/issues/128) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
